export const CONFIG={
 SUPABASE_URL:'https://YOUR-PROJECT.supabase.co',
 SUPABASE_ANON_KEY:'YOUR_PUBLISHABLE_OR_ANON_KEY',
 APP_NAME:'TAJER',
 SUBSCRIPTION_PRICE:5,
 SUBSCRIPTION_DAYS:30,
 DEFAULT_ASSETS:['XAU/USD','EUR/USD','GBP/USD','USD/JPY','BTC/USD']
};