create extension if not exists pgcrypto;
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 phone text, user_code char(16) unique not null,
 full_name text, role text not null default 'user' check(role in('user','admin')),
 status text not null default 'active' check(status in('active','blocked')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.assets(
 id bigint generated by default as identity primary key, symbol text unique not null, name text not null,
 category text, enabled boolean not null default true, sort_order int not null default 0,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.market_signals(
 id bigint generated by default as identity primary key, asset_id bigint references public.assets(id) on delete cascade,
 direction text not null check(direction in('BUY','SELL')), entry_price numeric not null, stop_loss numeric not null,
 take_profit_1 numeric, take_profit_2 numeric, strength numeric check(strength between 0 and 100),
 risk_level text check(risk_level in('LOW','MEDIUM','HIGH')), suggested_lot numeric, timeframe text,
 analysis text, status text not null default 'ACTIVE' check(status in('ACTIVE','HIT_TP','HIT_SL','EXPIRED','CANCELLED')),
 created_at timestamptz default now(), expires_at timestamptz, closed_at timestamptz
);
create table if not exists public.signal_targets(
 id bigint generated by default as identity primary key, signal_id bigint references public.market_signals(id) on delete cascade,
 target_number int not null, price numeric not null, status text default 'PENDING', created_at timestamptz default now()
);
create table if not exists public.subscriptions(
 id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete cascade,
 status text not null default 'pending' check(status in('pending','active','expired','cancelled')),
 plan text not null default '30_days', price numeric not null default 5, currency text not null default 'USDT',
 started_at timestamptz, expires_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.payment_requests(
 id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete cascade,
 user_code char(16), amount numeric not null default 5, currency text not null default 'USDT',
 network text, wallet_address text, screenshot_path text, txid text,
 status text not null default 'pending' check(status in('pending','approved','rejected')),
 admin_note text, reviewed_by uuid references public.profiles(id), reviewed_at timestamptz,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.notifications(
 id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete cascade,
 title text not null, message text not null, type text default 'system', signal_id bigint references public.market_signals(id) on delete set null,
 is_read boolean default false, created_at timestamptz default now()
);
create table if not exists public.user_settings(
 id uuid primary key references public.profiles(id) on delete cascade,
 notifications_enabled boolean default true, sound_enabled boolean default true, language text default 'ar', timezone text default 'Asia/Baghdad', updated_at timestamptz default now()
);
create table if not exists public.app_settings(
 id bigint generated by default as identity primary key, key text unique not null, value text, updated_at timestamptz default now()
);
create table if not exists public.admin_logs(
 id bigint generated by default as identity primary key, admin_id uuid references public.profiles(id) on delete set null,
 action text not null, target_type text, target_id text, details jsonb, created_at timestamptz default now()
);
create index if not exists idx_signals_status_created on public.market_signals(status,created_at desc);
create index if not exists idx_subscriptions_user on public.subscriptions(user_id,created_at desc);
create index if not exists idx_payments_user_status on public.payment_requests(user_id,status);
