-- Referral system: track who invited whom, and automatically grant the referrer
-- a free 30-day subscription once 3 people they referred purchase an activation.

alter table public.profiles add column if not exists referred_by uuid references public.profiles(id) on delete set null;
create index if not exists idx_profiles_referred_by on public.profiles(referred_by);

-- One row per free-month reward ever granted, so a referrer can never be rewarded twice
-- for the same batch of 3 (reward_batch 1 = referrals #1-3, batch 2 = #4-6, ...).
create table if not exists public.referral_rewards(
 id bigint generated by default as identity primary key,
 referrer_id uuid not null references public.profiles(id) on delete cascade,
 reward_batch int not null,
 subscription_id bigint references public.subscriptions(id) on delete set null,
 granted_at timestamptz not null default now(),
 unique(referrer_id,reward_batch)
);
alter table public.referral_rewards enable row level security;
create policy referral_rewards_self on public.referral_rewards for select using(referrer_id=auth.uid() or public.is_admin());

-- Called right after signup with the ref code captured from the invite link (?ref=...).
-- Silently no-ops on an invalid code, a self-referral, or if the user already has a referrer.
create or replace function public.set_referrer(p_ref_code text) returns void
language plpgsql security definer set search_path=public as $$
declare v_referrer uuid;
begin
 if p_ref_code is null or length(trim(p_ref_code))=0 then return; end if;
 select id into v_referrer from public.profiles where user_code=trim(p_ref_code);
 if v_referrer is null or v_referrer=auth.uid() then return; end if;
 update public.profiles set referred_by=v_referrer where id=auth.uid() and referred_by is null;
end;
$$;
grant execute on function public.set_referrer(text) to authenticated;

-- Grants any un-granted free-month batches a referrer has earned. Safe to call repeatedly.
create or replace function public.grant_referral_reward(p_referrer uuid) returns void
language plpgsql security definer set search_path=public as $$
declare v_qualified int; v_batch int; v_base timestamptz; v_new_sub bigint;
begin
 select count(distinct pr.id) into v_qualified
 from public.profiles pr
 where pr.referred_by=p_referrer
   and exists(select 1 from public.subscriptions s where s.user_id=pr.id and s.status='active');

 v_batch:=v_qualified/3;
 if v_batch<1 then return; end if;

 for i in 1..v_batch loop
  if not exists(select 1 from public.referral_rewards where referrer_id=p_referrer and reward_batch=i) then
   select greatest(coalesce(max(expires_at),now()),now()) into v_base from public.subscriptions where user_id=p_referrer and status='active';
   insert into public.subscriptions(user_id,status,plan,price,currency,started_at,expires_at)
    values(p_referrer,'active','referral_reward',0,'USDT',now(),v_base+interval '30 days')
    returning id into v_new_sub;
   insert into public.referral_rewards(referrer_id,reward_batch,subscription_id) values(p_referrer,i,v_new_sub);
   insert into public.notifications(user_id,title,message,type)
    values(p_referrer,'🎁 هدية الإحالة','مبروك! أحلت 3 أشخاص فعّلوا اشتراكهم، تم إضافة شهر كامل مجاني لحسابك.','system');
  end if;
 end loop;
end;
$$;

-- Fires whenever a subscription row becomes active; checks the paying user's referrer, if any.
create or replace function public.on_subscription_activated() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_referrer uuid;
begin
 if new.status='active' and (tg_op='INSERT' or old.status is distinct from 'active') then
  select referred_by into v_referrer from public.profiles where id=new.user_id;
  if v_referrer is not null then perform public.grant_referral_reward(v_referrer); end if;
 end if;
 return new;
end;
$$;
drop trigger if exists trg_subscription_activated on public.subscriptions;
create trigger trg_subscription_activated after insert or update on public.subscriptions
for each row execute function public.on_subscription_activated();

-- Read-only summary for the rewards screen: how many qualify, how many total invited,
-- how many free months already granted, and how many more are needed for the next one.
create or replace function public.get_my_referral_stats() returns table(
 qualified_count int, total_count int, rewards_granted int, remaining_for_next int
) language sql stable security definer set search_path=public as $$
 select
  (select count(distinct pr.id)::int from public.profiles pr where pr.referred_by=auth.uid()
    and exists(select 1 from public.subscriptions s where s.user_id=pr.id and s.status='active')),
  (select count(*)::int from public.profiles pr where pr.referred_by=auth.uid()),
  (select count(*)::int from public.referral_rewards where referrer_id=auth.uid()),
  (3-(
    (select count(distinct pr.id)::int from public.profiles pr where pr.referred_by=auth.uid()
      and exists(select 1 from public.subscriptions s where s.user_id=pr.id and s.status='active')) % 3
  )) % 3
$$;
grant execute on function public.get_my_referral_stats() to authenticated;

-- List of people the caller referred (name only), each marked whether they've activated yet.
-- Deliberately exposes nothing beyond name/date/status - not phone, email or user_code.
create or replace function public.get_my_referrals() returns table(
 full_name text, joined_at timestamptz, is_active boolean
) language sql stable security definer set search_path=public as $$
 select coalesce(pr.full_name,'مستخدم جديد'), pr.created_at,
  exists(select 1 from public.subscriptions s where s.user_id=pr.id and s.status='active')
 from public.profiles pr where pr.referred_by=auth.uid() order by pr.created_at desc
$$;
grant execute on function public.get_my_referrals() to authenticated;
